CREATE DATABASE IF NOT EXISTS task;

USE task;

CREATE TABLE IF NOT EXISTS tasks (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name_task VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL
);